---
apiVersion: v1
kind: Secret
metadata:
  name: rs-sapig-secrets
type: Opaque
data:
 IG_AGENT_ID: {{ .Values.secrets.igAgentID }}
 IG_AGENT_PASSWORD: {{ .Values.secrets.igAgentPassword }}
 IG_CLIENT_ID: {{ .Values.secrets.igClientID }}
 IG_CLIENT_SECRET: {{ .Values.secrets.igClientSecret }}
 IG_IDM_USER: {{ .Values.secrets.igIDMUser }}
 IG_IDM_PASSWORD: {{ .Values.secrets.igIDMPassword }}