---
apiVersion: {{ .Values.service.apiVersion }}
kind: Service
metadata:
  name: fapi-pep-rs
  labels:
    app: fapi-pep-rs
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: fapi-pep-rs
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{  .Values.service.protocol }}
  selector:
    app: fapi-pep-rs
---
apiVersion: {{ .Values.service.apiVersion }}
kind: Service
metadata:
  name: {{ .Chart.Name }}-admin
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Chart.Name }}-admin
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPortAdmin }}
      protocol: {{  .Values.service.protocol }}
  selector:
    app: {{ .Chart.Name }}