apiVersion: v1
kind: Secret
metadata:
  name: rs-sapig-secrets
type: Opaque
data:
# IG_AGENT_ID: aWctYWdlbnQ=
# IG_AGENT_PASSWORD: cGFzc3dvcmQ=
# IG_CLIENT_ID: aWctY2xpZW50
# IG_CLIENT_SECRET: cGFzc3dvcmQ=
# IG_METRICS_USERNAME: dXNlcg==
# IG_METRICS_PASSWORD: cGFzc3dvcmQ=
# IG_TRUSTSTORE_PASSWORD: Y2hhbmdlaXQ=