apiVersion: v1
kind: Service
metadata:
  name: fapi-pep-rs
spec:
  ports:
    - name: fapi-pep-rs
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: fapi-pep-rs
  type: ClusterIP